[package]
name = "resvg-wrapper"
version = "1.0.0"
edition = "2021"

[lib]
name = "resvg_wrapper"
crate-type = ["cdylib"]

[dependencies]
resvg = "0.43"
usvg = "0.43"
tiny-skia = "0.11"
fontdb = "0.22"

[profile.release]
lto = true
opt-level = 3
strip = true